business/urls.py
from django.contrib import admin
from django.urls import (
    path,
    include
)
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('transactions.urls')),
    path('stocks/', include('stocks.urls')),
    path('authentication/', include('authentication.urls')),
]

stocks/urls.py
from django.urls import path
from . import views

from django.views.decorators.csrf import csrf_exempt

urlpatterns = [
    path('', views.index, name="stocks"),
    path('add-stock', views.add_stock, name="add-stock"),
    path('edit-stock/<int:id>', views.edit_stock, name="edit-stock"),
    path('delete-stock/<int:id>', views.delete_stock, name="delete-stock"),
]

stocks/models.py
from django.db import models
from django.contrib.auth.models import User

from business.utils.modelling import ExternalBase


class Stock(ExternalBase):  
    """ Region Model """

    id = models.CharField(
        primary_key=True, 
        null=False,
        blank=False,
        max_length=20,
        verbose_name = "Stock ID"
    )

    name = models.CharField(
        max_length=256, 
        null=False, 
        blank=False,
        unique=True,
        verbose_name = "Stock Name"
    )

    owner = models.ForeignKey(
        User, 
        on_delete=models.CASCADE
    )

    def __str__(self):
        """String representation of the model."""
        return str(self.name)

    class Meta:
        """Meta Data."""

        verbose_name = 'Stock'
        verbose_name_plural = 'Stocks'
        ordering = ['-updated_at']

stocks/views.py
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from django.contrib import messages
from django.db import IntegrityError
from django.contrib.auth.decorators import login_required

from .models import Stock


@login_required(login_url='/authentication/login')
def index(request):
    user = request.user

    # showing all if the user is superuser
    if(user.is_superuser):
        stocks = Stock.objects.all()
    else:
        stocks = Stock.objects.filter(owner=user)

    # pagination
    paginator = Paginator(stocks, 10)
    page_number = request.GET.get('page')
    page_obj = Paginator.get_page(paginator, page_number)

    context = {
        'page_obj': page_obj
    }

    return render(request, 'stocks/index.html', context)


@login_required(login_url='/authentication/login')
def add_stock(request):
    try:
        stocks = Stock.objects.all()
        context = {
            'values': request.POST
        }

        # Handling GET request
        if request.method == 'GET':
            return render(request, 'stocks/add_stock.html', context)

        # Handling GET request
        if request.method == 'POST':
            stock_id = request.POST['stock_id']
            stock_name = request.POST['stock_name']

            # validating the form
            # checking completeness
            if not stock_name:
                messages.error(request, 'Name is required')
                return render(request, 'stocks/add_stock.html', context)

            # handling duplicacy
            stock_count = stocks.filter(name__iexact = stock_name).count()
            if(stock_count == 1):
                messages.error(request, 'Stock Name already present')
                return render(request, 'stocks/add_stock.html', context)
                
            try:
                Stock.objects.create(owner=request.user, id=stock_id, name=stock_name)
            except IntegrityError as e:
                messages.error(request, 'Invalid Input, Try again!')

            messages.success(request, 'Stock saved successfully')

            return redirect('stocks')
    except Exception as e:
        messages.error(request, f'Something went wrong while adding stock : {e}')
        return redirect('stocks')


@login_required(login_url='/authentication/login')
def edit_stock(request, id):
    try:
        stocks = Stock.objects.all()
        stock = Stock.objects.get(pk=id)

        context = {
            'stock': stock,
        }

        # Handling GET request
        if request.method == 'GET':
            return render(request, 'stocks/edit_stock.html', context)

        # Handling POST request
        if request.method == 'POST':
            stock_name = request.POST['stock_name']
            stock_id = request.POST['stock_id']

            # checking for completeness of the form
            if not stock_name:
                messages.error(request, 'Name is required')
                return render(request, 'stocks/edit_stock.html', context)
            
            # assigning changed values to the object
            user = request.user
            stock.id = stock_id
            stock.name = stock_name
            stock.owner = user

            # saving the stock object
            stock.save()
            messages.success(request, f'{stock_name} updated  successfully')
            return redirect('stocks')
    except Exception as e:
        messages.error(request, f'Something went wrong while editing stock : {e}')
        return redirect('stocks')


def delete_stock(request, id):
    try:
        stock = Stock.objects.get(pk=id)
        # Handling POST request
        if request.method == 'POST':
            stock.delete()
            messages.success(request, 'Stock Deleted')
            return redirect('stocks')

        # Rendering the delete item page
        return render(request, 'partials/_delete_item.html', {'item' : stock})
    except Exception as e:
        # Error Handling
        messages.error(request, f'Something went wrong while deleting stock : {e}')
        return redirect('stocks')

templates/stocks/add_stock.html
{% extends 'base.html' %} {% block content %}

<div class="container mt-4 main-container edit-card">
  <div class="card">
    <div class="card-body">
      <form action="{% url 'add-stock' %}" method="post">
        {% include 'partials/_messages.html'%} 
        {% csrf_token %}
        <div class="form-group">
          <label for="">Stock ID</label>
          <input
            type="text"
            class="form-control form-control-sm"
            name="stock_id"
            value="{{values.stock_id}}"
          />
        </div>
        <div class="form-group">
          <label for="">Stock Name</label>
          <input
            type="text"
            class="form-control form-control-sm"
            name="stock_name"
            value="{{values.stock_name}}"
          />
        </div>

        {% include 'partials/_add_buttons.html' %}
      </form>
    </div>
  </div>
</div>

{% endblock %}

templates/stocks/edit_stock.html
{% extends 'base.html' %} {% block content %}

<div class="container mt-4 main-container edit-card">
  <div class="row">
    <div class="col mt-3 pb-3">
      Edit {{stock.name}} Stock
    </div>
  </div>

  <div class="card">
    <div class="card-body">
      <form action="{% url 'edit-stock' stock.id %}" method="post">
        {% include 'partials/_messages.html'%} 
        {% csrf_token %}
        <div class="form-group">
          <label for="">Stock ID</label>
          <input
            type="text"
            class="form-control form-control-sm"
            name="stock_id"
            value="{{stock.id}}"
            readonly
          />
        </div>
        <div class="form-group">
          <label for="">Stock Name</label>
          <input
            type="text"
            class="form-control form-control-sm"
            name="stock_name"
            value="{{stock.name}}"
          />
        </div>

        {% include 'partials/_edit_buttons.html' %}
      </form>
    </div>
  </div>
</div>

{% endblock %}

templates/stocks/index.html
{% extends 'base.html' %}
{% load static %}



{% block content %}
<div class="container mt-4 main-container">
  <div class="row">
    <div class="col-md-12">
      {% include 'partials/_messages.html' %}
    </div>
  </div>
  
    <div class="row">
      <div class="col-md-10">
      </div>
      <div class="col-md-2">
        <!-- If user has add permission -->
        {% if perms.stocks.add_stock %}
          <a href="{% url 'add-stock'%}" class="btn btn-primary">Add Stock</a>
        {% endif %}
      </div>
    </div>
    <!-- If user has view permission -->
    {% if perms.stocks.view_stock %}
      {% for stock in page_obj%}
        <div class="update-delete-fn">
          <!-- If user has change permission -->
          {% if perms.stocks.change_stock %}
            <a href="{% url 'edit-stock' stock.id  %}" title="Edit">
              <i class="fa fa-edit" style="font-size:25px"></i>
            </a>
          {% endif %}
          
          <!-- If user has delete permission -->
          {% if perms.stocks.delete_stock %}
            <a href="{% url 'delete-stock' stock.id  %}" title="Delete">
              <i class="fa fa-trash" style="font-size:25px"></i>
            </a>
          {% endif %}
        </div>

        <button class="accordion mt-3">{{stock.name}}</button>
        <div class="panel">
          <div class="app-table">
            <table class="table table-stripped table-hover">
              <thead>
                <tr>
                  <th>Stock ID</th>
                  <th>Stock Name</th>
                </tr>
              </thead>

              <tbody>
                <tr>
                  <td>{{stock.id}}</td>
                  <td>{{stock.name}}</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      {% endfor %}

      {% include 'partials/_pagination.html' %}
    {% else %}
      No permission on Stocks!
    {% endif %}
</div>
{% endblock content %}