business/urls.py
from django.contrib import admin
from django.urls import (
    path,
    include
)
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('transactions.urls')),
    path('stocks/', include('stocks.urls')),
    path('authentication/', include('authentication.urls')),
]

stocks/urls.py
from django.urls import path
from . import views

from django.views.decorators.csrf import csrf_exempt

urlpatterns = [
    path('', views.index, name="stocks"),
    path('add-stock', views.add_stock, name="add-stock"),
    path('edit-stock/<int:id>', views.edit_stock, name="edit-stock"),
    path('delete-stock/<int:id>', views.delete_stock, name="delete-stock"),
]

transactions/urls.py
from django.urls import path
from . import views

# from django.views.decorators.csrf import csrf_exempt

urlpatterns = [
    path('', views.dashboard, name="dashboard"),
    path('transactions', views.index, name="transactions"),
    path('add-transaction', views.add_transaction, name="add-transaction"),
    path('edit-transaction/<int:id>', views.edit_transaction, name="edit-transaction"),
    path('delete-transaction/<int:id>', views.delete_transaction, name="delete-transaction"),
]

transactions/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.timezone import now

from business.utils.modelling import ExternalBase
from stocks.models import Stock


class Transaction(ExternalBase):  
    """ Region Model """

    id = models.CharField(
        primary_key=True, 
        null=False,
        blank=False,
        max_length=20,
        verbose_name = "Transaction ID"
    )

    date = models.DateField(
        default=now,
        verbose_name="Transaction Date"
    )

    stock_id = models.ForeignKey(
        Stock,
        blank=True,
        null=True,
        related_name="stock_id",
        on_delete=models.CASCADE,
        verbose_name="Stock ID",
        editable=False
    )

    stock_name = models.ForeignKey(
        Stock,
        blank=True,
        null=True,
        related_name="stock_name",
        on_delete=models.CASCADE,
        verbose_name="Stock Name"
    )

    stock_price = models.PositiveIntegerField(
        null=False, 
        blank=False,
        verbose_name = "Stock Price",
        default=1
    )

    stock_quantity = models.PositiveIntegerField(
        null=False, 
        blank=False,
        verbose_name = "Stock Quantity",
        default=1
    )

    owner = models.ForeignKey(
        User, 
        on_delete=models.CASCADE,
    )

    def __str__(self):
        """String representation of the model."""
        return str(self.id)

    class Meta:
        """Meta Data."""

        verbose_name = 'Transaction'
        verbose_name_plural = 'Transactions'

transactions/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.contrib import messages
from django.db import IntegrityError, DataError

from transactions.models import Transaction
from stocks.models import Stock


@login_required(login_url='/authentication/login')
def dashboard(request):
    # redirecting to transactions page
    return redirect('transactions')


@login_required(login_url='/authentication/login')
def index(request):
    user = request.user

    # Show all if the user is superuser
    if(user.is_superuser):
        transactions = Transaction.objects.all()
    else:
        transactions = Transaction.objects.filter(owner=user)

    # Pagination
    paginator = Paginator(transactions, 10)
    page_number = request.GET.get('page')
    page_obj = Paginator.get_page(paginator, page_number)

    context = {
        'page_obj': page_obj
    }

    return render(request, 'transactions/index.html', context)


@login_required(login_url='/authentication/login')
def add_transaction(request):
    try:
        transactions = Transaction.objects.all()
        stocks = Stock.objects.all()
        error_msg = ''

        context = {
            'values': request.POST,
            'stocks': stocks
        }

        # Handling GET request
        if request.method == 'GET':
            return render(request, 'transactions/add_transaction.html', context)

        # Handling POST request
        if request.method == 'POST':
            post_data = request.POST
            stock_name = post_data['stock_name']
            stock_price = post_data['stock_price']
            stock_quantity = post_data['stock_quantity']
            transaction_date = post_data['transaction_date']
            transaction_id = post_data['transaction_id']

            # Check for completeness of the form
            if not transaction_date:
                error_msg = 'Date is required'

            if not stock_quantity:
                error_msg = 'Quantity is required'

            if not stock_price:
                error_msg = 'Price is required'

            if not transaction_id:
                error_msg = 'ID is required'
            
            if error_msg != '':
                messages.error(request, error_msg)
                return render(request, 'transactions/add_transaction.html', context)

            stock = stocks.filter(name__iexact = stock_name).first()

            # Creating the transaction and saving it to DB
            try:
                Transaction.objects.create( 
                    id=transaction_id,
                    date=transaction_date,
                    stock_id=stock,
                    stock_name=stock,
                    stock_price=stock_price,
                    stock_quantity=stock_quantity,
                    owner=request.user
                )
            except IntegrityError as e:
                # This is raised when the values dont follow the DB model constraints
                messages.error(request, 'Invalid Input, Try again!')
                return render(request, 'transactions/add_transaction.html', context)
            except DataError as de:
                # This is raised when the values do not follow limit ranges
                messages.error(request, 'ID should less than or equal to 20 characters')
                return render(request, 'transactions/add_transaction.html', context)

            messages.success(request, 'Transaction saved successfully')

            # Redirecting to the transactions page
            return redirect('transactions')

    except Exception as e:
        messages.error(request, f'Something went wrong while adding transaction : {e}')
        return redirect('transactions')

@login_required(login_url='/authentication/login')
def edit_transaction(request, id):
    try:
        transaction = Transaction.objects.get(pk=id)
        stocks = Stock.objects.all()
        error_msg = ''

        context = {
            'transaction': transaction,
            'stocks': stocks
        }

        if request.method == 'GET':
            # render the edit page on GET call
            return render(request, 'transactions/edit_transaction.html', context)

        if request.method == 'POST':
            # pulling data from POST request
            post_data = request.POST
            stock_name = post_data['stock_name']
            stock_price = post_data['stock_price']
            stock_quantity = post_data['stock_quantity']
            transaction_date = post_data['transaction_date']
            transaction_id = post_data['transaction_id']

            # check for completeness of the form
            if not transaction_date:
                error_msg = 'Date is required'

            if not stock_quantity:
                error_msg = 'Quantity is required'

            if not stock_price:
                error_msg = 'Price is required'
            
            # handling the error messages with proper logging
            if error_msg != '':
                messages.error(request, error_msg)
                return render(request, 'transactions/edit_transaction.html', context)

            # for Stock ID
            stock = stocks.filter(name__iexact = stock_name).first()

            # adding the changed values
            transaction.id = transaction_id
            transaction.date = transaction_date
            transaction.stock_id = stock
            transaction.stock_name = stock
            transaction.stock_price = stock_price
            transaction.stock_quantity = stock_quantity
            transaction.owner = request.user

            # Saving the transaction
            transaction.save()

            messages.success(request, f'{transaction_id } updated successfully')
            return redirect('transactions')
    except Exception as e:
        messages.error(request, f'Something went wrong while editing transaction : {e}')
        return redirect('transactions')



def delete_transaction(request, id):
    try:
        # Pulling particular transaction from the DB
        transaction = Transaction.objects.get(pk=id)
        # Handling POST request
        if request.method == 'POST':
            # deleting the transaction
            transaction.delete()
            # Showing deleted message to the user
            messages.success(request, 'Transaction Deleted')
            # Redirecting to the transactions page
            return redirect('transactions')

        return render(request, 'partials/_delete_item.html', {'item' : transaction})
    except Exception as e:
        messages.error(request, f'Something went wrong while deleting transaction : {e}')
        return redirect('transactions')

templates/transactions/add_transaction.html
{% extends 'base.html' %} 
{% block content %}

<div class="container mt-4 main-container edit-card">
  <div class="card">
    <div class="card-body">
      <form action="{% url 'add-transaction' %}" method="post">
        {% include 'partials/_messages.html'%}
        {% csrf_token %}

        <div class="form-group">
          <label for="">Transaction ID</label>
          <input
            type="text"
            class="form-control form-control-sm"
            name="transaction_id"
            value="{{values.transaction_id}}"
          />
        </div>

        <div class="form-group">
          <label for="">Stock Name</label>
          <select class="form-control" name="stock_name">
            {% for stock in stocks %}
            <option name="stock" value="{{stock.name}}"
              >{{stock.name}}</option
            >
            {% endfor %}
          </select>
        </div>


        <div class="form-group">
          <label for="">Stock Price</label>
          <input
            type="text"
            class="form-control form-control-sm"
            name="stock_price"
            value="{{values.stock_price}}"
          />
        </div>

        <div class="form-group">
          <label for="">Stock Quantity</label>
          <input
            type="text"
            class="form-control form-control-sm"
            name="stock_quantity"
            value="{{values.stock_quantity}}"
          />
        </div>

        <div class="form-group">
          <label for="">Transaction Date</label>
          <input
            type="date"
            class="form-control form-control-sm"
            name="transaction_date"
            value="{{values.transaction_date |date:'Y-m-d' }}"
          />
        </div>

        {% include 'partials/_add_buttons.html' %}
      </form>
    </div>
  </div>
</div>

{% endblock %}

templates/transactions/edit_transaction.html
{% extends 'base.html' %} 
{% block content %}

<div class="container mt-4 main-container edit-card">
  <div class="row">
    <div class="col mt-3 pb-3">
      Edit transaction: {{transaction.id}}
    </div>
  </div>

  <div class="card">
    <div class="card-body">
      <form action="{% url 'edit-transaction' transaction.id %}" method="post">
        {% include 'partials/_messages.html'%} 
        {% csrf_token %}

        <div class="form-group">
          <label for="">Transaction ID</label>
          <input
            type="text"
            class="form-control form-control-sm"
            name="transaction_id"
            value="{{transaction.id}}"
            readonly
          />
        </div>

        <div class="form-group">
          <label for="">Stock Name</label>
          <select class="form-control" name="stock_name">
            {% for stock in stocks %}
            <option name="stock" value="{{stock.name}}"
              >{{stock.name}}</option
            >
            {% endfor %}
          </select>
        </div>


        <div class="form-group">
          <label for="">Stock Price</label>
          <input
            type="text"
            class="form-control form-control-sm"
            name="stock_price"
            value="{{transaction.stock_price}}"
          />
        </div>

        <div class="form-group">
          <label for="">Stock Quantity</label>
          <input
            type="text"
            class="form-control form-control-sm"
            name="stock_quantity"
            value="{{transaction.stock_quantity}}"
          />
        </div>

        <div class="form-group">
          <label for="">Transaction Date</label>
          <input
            type="date"
            class="form-control form-control-sm"
            name="transaction_date"
            value="{{transaction.date |date:'Y-m-d' }}"
          />
        </div>

        {% include 'partials/_edit_buttons.html' %}

      </form>
    </div>
  </div>
</div>

{% endblock %}

templates/transactions/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container mt-4 main-container">
  <div class="row">
    <div class="col-md-12">
      {% include 'partials/_messages.html' %}
    </div>
  </div>

  <div class="row">
    <div class="col-md-10">
    </div>
    <div class="col-md-2">
      {% if perms.transactions.add_transaction %}
        <a href="{% url 'add-transaction'%}" class="btn btn-primary">Add Transaction</a>
      {% endif %}
  </div>
  </div>
  {% if perms.transactions.view_transaction %}
    {% for transaction in page_obj%}
      <div class="update-delete-fn">
        <!-- If user has change permission -->
        {% if perms.transactions.change_transaction %}
          <a href="{% url 'edit-transaction' transaction.id  %}" title="Edit">
            <i class="fa fa-edit" style="font-size:25px"></i>
          </a>
        {% endif %}
        
        <!-- If user has delete permission -->
        {% if perms.transactions.delete_transaction %}
          <a href="{% url 'delete-transaction' transaction.id  %}" title="Delete">
            <i class="fa fa-trash" style="font-size:25px"></i>
          </a>
        {% endif %}
      </div>

      <button class="accordion mt-3">{{transaction.id}}</button>
      <div class="panel">
        <div class="app-table">
          <table class="table table-stripped table-hover">
            <thead>
              <tr>
                <th>Date</th>
                <th>Stock name</th>
                <th>Stock Price</th>
                <th>Stock Quantity</th>
              </tr>
            </thead>
      
            <tbody>
              <tr>
                <td>{{transaction.date}}</td>
                <td>{{transaction.stock_name}}</td>
                <td>{{transaction.stock_price}}</td>
                <td>{{transaction.stock_quantity}}</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    {% endfor %}
    
    {% include 'partials/_pagination.html' %}
  {% else %}
      No permission on transactions!
  {% endif %}
  
</div>
{% endblock content %}